### ISSUE TITLE
Android BackButton Pressed issue

### ISSUE THREAD

**Issue by susyl13** [rohitvipin/Xamarin-Forms-Custom-Renderer-Samples#1]
First i enter into some other page and When i navigate back to the page where i implement search button on toolbar, the search button gets disappear. What had happened, could you please suggest me some ideas??

**Comment by rohitvipin** [comment]
I have not tried navigation from the search page. I'll try and update you.

**Comment by susyl13** [comment]
ok thanks please update asap if possible .

**Comment by susyl13** [comment]
Hey, don't you have tried yet?

**Comment by rohitvipin** [comment]
It's not my primary project, the source code is available for free if you want to have a look at it.

**Comment by susyl13** [comment]
i have looked and used it successfully, it performs accurately while moving forward navigation but when i move backward to that page, the renderer doesnot work correctly. i have researched various sites but cannot found correct answer. please i am in critical condition suggest me some ideas about recreating toolbar while doing back navigation. It will be very thankful for me to complete my project.

**Comment by rohitvipin** [comment]
I really understand the situation but I won't be able to look at this immediately.
You can  look at re creating the controls in the on appearing event.

**Comment by michaelmontero** [comment]
@susyl13 have you solved the problem?

**Comment by rohitvipin** [comment]
You can add events for Element OnAppearing and OnDisappearing to re-add the search view.

**Comment by michaelmontero** [comment]
Thank you @rohitvipin. I'll create a pull request when i fix it.

**Comment by michaelmontero** [comment]
Hey @rohitvipin i've write the code you suggest, but i did not get the solution. 

When i press back button in other page, both method are hinted, and the AddSearchToToolBar method run correctly, but the SearchView does not appear. Any Suggestion?

Here is the code: https://gist.github.com/michaelmontero/9c8736c5987c26857ae62b151e651ac7
