### ISSUE TITLE
FindViewById in latest android versions

### ISSUE THREAD

**Issue by ChummerUA** [rohitvipin/Xamarin-Forms-Custom-Renderer-Samples#11]
You should use LayoutInflater before FindViewById to get toolbar in latest android versions. Here's sample of my OnElementChanged event for SearchPageRender
```
var inflater = LayoutInflater.From(MainActivity.Current);

var toolbarView = inflater.Inflate(Resource.Layout.Toolbar, null);
var toolbar = MainActivity.Current.FindViewById<Android.Support.V7.Widget.Toolbar>(toolbarView.Id);

MainActivity.ToolBar = toolbar;
```
I was getting null from FindViewById without using the inflater first

**Comment by rohitvipin** [comment]
Please create a PR and I can merge it.
I haven't updated the sample since I initially wrote it.
