### ISSUE TITLE
No success. 

### ISSUE THREAD

**Issue by tombby11** [rohitvipin/Xamarin-Forms-Custom-Renderer-Samples#3]
I have tried to make what you did in your blog but no luck 
`"ToolBar = FindViewById<toolbar>(Resource.Id.toolbar);"  `
is always null  . 
I have even tried your sample and still nothing works . is it Android Version related? I am using Nougat emulator .

**Comment by rohitvipin** [comment]
You can try to cast the Xamarin forms context into activity and do find by view on that. You will have to do it in the onElementChanged of the custom render.

**Comment by rohitvipin** [comment]
I have not run much in emulator. I have it working in real devices.

**Comment by patricksegantine** [comment]
hi,
I have tried run this project in my Samsung S6 edge with Android N, but don't work... please help me... the project running without searchbar...

**Comment by interCreaciones** [comment]
@ptrkseg, Could you solve it?

**Comment by rohitvipin** [comment]
Make sure you are having the latest Xamarin, VS, X.F, Android SDKs and support libraries.
