### ISSUE TITLE
System.ArgumentException: Handle must be valid. Parameter name: instance

### ISSUE THREAD

**Issue by interCreaciones** [rohitvipin/Xamarin-Forms-Custom-Renderer-Samples#4]
Hi!Thanks to your example, I have been able to implement it, but I have a problem. I have a "master detail" structure when I click on a menu, a new navigation page appears with a search button, when I click it appears the error and broke in this line:
MainActivity.ToolBar.Title = Element.Title;
Thanks!

**Comment by rohitvipin** [comment]
Can you do a null check? Also instead of using the static version of the toolbar you can find it when required from by casting your xamarin.forms context as an activity. Then you will be able to do FindByView for the toolbar.

**Comment by interCreaciones** [comment]
Thanks, this has worked for me!
