### ISSUE TITLE
OnCreateOptionsMenu is not accessible in nougat.

### ISSUE THREAD

**Issue by rakeshdkaatkar** [rohitvipin/Xamarin-Forms-Custom-Renderer-Samples#7]
This is not working in nougat can u please give a fix for this

**Comment by ghost** [comment]
Doesn't appear to work in either Nougat or Oreo, no search components appear at all

**Comment by rohitvipin** [comment]
It seems an issue with the current version of xamarin forms. Instead of OnCreateOptionsMenu you can use OnElementChanged in the custom renderer and use CrossActivity plugin and find the toolbar by Id.
